In [4]:
import numpy as np
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])

print(np1.ndim) #維度
print(np1.shape) #形狀
print(np1.dtype) #資料型態

1
(3,)
int64


In [6]:
#建立填滿0或1的陣列

np1 = np.zeros([2,3],int)  # ([2列,3欄],dtype:int) 的 0

np2 = np.ones([3,2],int)   # ([3列,2欄],dtype:int) 的 1

print(np1)
print(np2)

[[0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]
 [1 1]]


In [8]:
建立填滿特定數的陣列

np1 = np.full((3,2),4,float)
print(np1)

np2 = np.eye(5)  #(大小,M=指定col,k=初始位置,dtype)

print(np2)

[[4. 4.]
 [4. 4.]
 [4. 4.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
np1 = np.linspace(1,10,5,1,0,dtype=int)#(開始,結束,間距,結尾值(1(True)or 0(False),回傳模式(1(True)or 0(False),dtype)
print(np1)       
np2 = np.linspace(1,10,5,1,1,dtype=int)
print(np2)
np3 = np.linspace(1,10,5,0,0,dtype=int)

np4 = np.arange(10)  #(開始,結束,間距，資料型態)

[ 1  3  5  7 10]
(array([ 1,  3,  5,  7, 10]), 2.25)


In [15]:
#dot

data1 = np.array([[4,5,6],[7,8,9],[10,11,12]])
data2 = np.array([[3,1,2],[2,3,1],[1,2,3]])

print(np.dot(data1,data2))
print(data1.dot(data2))

[[28 31 31]
 [46 49 49]
 [64 67 67]]
[[28 31 31]
 [46 49 49]
 [64 67 67]]
